name: price_service_sdk
description: A Dart SDK for pyth price service SDK.
version: 1.0.0
repository: https://github.com/jovinlidan/price-service-sdk-dart

environment:
  sdk: ^3.9.0

dependencies:
  decimal: ^3.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.11.0
  lints: ^6.0.0
  test: ^1.25.6
